version: '3'

services:
  web:
    build:
      context: ./app
      dockerfile: ./app/Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - flask-app-network

    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    volumes:
      - ./bd:/docker-entrypoint-initdb.d
